# This file contains the configuration settings for your Redwood app.
# This file is also what makes your Redwood app a Redwood app.
# If you remove it and try to run `yarn rw dev`, you'll get an error.
#
# For the full list of options, see the "App Configuration: redwood.toml" doc:
# https://redwoodjs.com/docs/app-configuration-redwood-toml

[web]
  title = "MeetEo"
  port = 8910
  apiUrl = "/.netlify/functions"
  includeEnvironmentVariables = [
    "AUTH0_DOMAIN",
    "AUTH0_CLIENT_ID",
    "AUTH0_REDIRECT_URI",
    "AUTH0_AUDIENCE"
  ]
[api]
  port = 8911
  includeEnvironmentVariables = ["ANTHROPIC_API_KEY", "OPENWEATHER_API_KEY", "AUTH0_DOMAIN", "AUTH0_CLIENT_ID", "AUTH0_REDIRECT_URI", "AUTH0_AUDIENCE"]
[browser]
  open = true
[notifications]
  versionUpdates = ["latest"]
